name: test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          cache: "yarn"
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
